<div class="direction-vn">
	<div class="container">
		<div class="row">
			<div class="col-md-9">
				<h3 class="text-center">
					Mind&Body
				</h3>
				<div class="b-direction-vn">
					<div class="col-md-5">
						<div class="direction-vn__item">
							<div class="direct-top"></div>
							<img src="img/direction-vn.png" alt="направление" class="img-responsive">
							<div class="direct-bottom"></div>
						</div>
					</div>
					<div class="col-md-7">
						<p>
							Ты давно хочешь привести свою фигуру в поорядок? Ты хочешь стать еще более уверенной в себе? Тогда скорее приходи в школу танцев Top-Dance на авторскую фитнес-программу Mind&Body. Красивая фигура требует постоянных тренировок! Если тебе хочется изменить свою жизнь, то все начинается с преобразования своегоо тела.
						<!-- </p>
						<p> -->
							Представляем вашему вниманию авторскую фитнес - программу Дарьи Коротковой &mdash; Mind&Body, в школе танцев Top-Dance. Это специальный комплекс упражнений, направленный на совершенствование и корректировку фигуры, проработку всех групп мышц и поддержание тонуса всего организма.
						</p>
						<div class="check-list">
							<p>В чем приходить:</p>
							<ul class="list-unstyled">
								<li>
									<label>
										<input type="checkbox" class="check-box" checked>
										Платье
									</label>
								</li>
								<li>
									<label>
										<input type="checkbox" class="check-box" checked>
										Каблуки
									</label>
								</li>
							</ul>
						</div>
					</div>
				</div>
				<div class="direction-vn_item">
					<h3 class="text-center">
						Педагоги по Mind&Body
					</h3>
					<div class="row">
						<div id="owl-one" class="owl-carousel">
		                    <div> 
		                            <div class="block">
		                            	<img alt="" src="img/direction.png">
		                            	<div class="b-block">
		                            		<div class="b-block__item">
		                            			<h4>Короткова Дарья</h4>
		                            			<p><a href="#">Педагоги по Mind&Body</a></p>
		                            		</div>
		                            	</div>
		                            </div>
		                    </div>
		                    <div>
		                            <div class="block">
		                            	<img alt="" src="img/direction.png">
		                            	<div class="b-block">
		                            		<div class="b-block__item">
		                            			<h4>Короткова Дарья</h4>
		                            			<p><a href="#">Педагоги по Mind&Body</a></p>
		                            		</div>
		                            	</div>
		                            </div>
		                    </div>
		                    <div>
		                            <div class="block">
		                            	<img alt="" src="img/direction.png">
		                            	<div class="b-block">
		                            		<div class="b-block__item">
		                            			<h4>Короткова Дарья</h4>
		                            			<p><a href="#">Педагоги по Mind&Body</a></p>
		                            		</div>
		                            	</div>
		                            </div>
		                    </div>
		                    <div>
		                            <div class="block">
		                            	<img alt="" src="img/direction.png">
		                            	<div class="b-block">
		                            		<div class="b-block__item">
		                            			<h4>Короткова Дарья</h4>
		                            			<p><a href="#">Педагоги по Mind&Body</a></p>
		                            		</div>
		                            	</div>
		                            </div>
		                    </div>
		                    <div>
		                            <div class="block">
		                            	<img alt="" src="img/direction.png">
		                            	<div class="b-block">
		                            		<div class="b-block__item">
		                            			<h4>Короткова Дарья</h4>
		                            			<p><a href="#">Педагоги по Mind&Body</a></p>
		                            		</div>
		                            	</div>
		                            </div>
		                    </div>
		                    <div>
		                            <div class="block">
		                            	<img alt="" src="img/direction.png">
		                            	<div class="b-block">
		                            		<div class="b-block__item">
		                            			<h4>Короткова Дарья</h4>
		                            			<p><a href="#">Педагоги по Mind&Body</a></p>
		                            		</div>
		                            	</div>
		                            </div>
		                    </div>
		                    <div>
		                            <div class="block">
		                            	<img alt="" src="img/direction.png">
		                            	<div class="b-block">
		                            		<div class="b-block__item">
		                            			<h4>Короткова Дарья</h4>
		                            			<p><a href="#">Педагоги по Mind&Body</a></p>
		                            		</div>
		                            	</div>
		                            </div>
		                    </div>
		                </div>
					</div>
					<div class="direction-vn__video">
						<h3 class="text-center">
							Видео
						</h3>
						<div class="row">
							<div id="owl-example" class="owl-carousel">
			                    <div> 
			                        <a class="thumbnail" href="#">
			                            <img alt="" src="img/play.png">
			                        </a>
			                    </div>
			                    <div>
			                        <a class="thumbnail" href="#">
			                            <img alt="" src="img/play.png">
			                        </a>
			                    </div>
			                    <div>
			                        <a class="thumbnail" href="#">
			                            <img alt="" src="img/play.png">
			                        </a>
			                    </div>
			                    <div>
			                        <a class="thumbnail" href="#">
			                            <img alt="" src="img/play.png">
			                        </a>
			                    </div>
			                    <div>
			                        <a class="thumbnail" href="#">
			                            <img alt="" src="img/play.png">
			                        </a> 
			                    </div>
			                    <div>
			                        <a class="thumbnail" href="#">
			                            <img alt="" src="img/play.png">
			                        </a>
			                    </div>
			                    <div>
			                        <a class="thumbnail" href="#">
			                            <img alt="" src="img/play.png">
			                        </a>
			                    </div>
			                </div>
						</div>
					</div>
					<div class="photo">
						<h3 class="text-center">
							Наши фото
						</h3>
						<div class="col-md-3">
							<img src="img/photos.png" alt="Фотографии" class="img-responsive">
						</div>
						<div class="col-md-3">
							<img src="img/photos.png" alt="Фотографии" class="img-responsive">
						</div>
						<div class="col-md-3">
							<img src="img/photos.png" alt="Фотографии" class="img-responsive">
						</div>
						<div class="col-md-3">
							<img src="img/photos.png" alt="Фотографии" class="img-responsive">
						</div>
						<div class="photo-button">
							<button class="btn btn-default" type="button">
								Посмотреть все
							</button>
						</div>
					</div>
					<div class="direction-vn__table">
						<table>
							<thead>
								<tr>
									<th>
										Понедельник
									</th>
									<th>
										Вторник
									</th>
									<th>
										Среда
									</th>
									<th>
										Четверг
									</th>
									<th>
										Пятница
									</th>
									<th>
										Суббота
									</th>
									<th>
										Воскресенье
									</th>
								</tr>
							</thead>
							<tbody>
								<tr class="primary-tab">
									<td>
										12:00-13:00 <br>
										Открытый урок!! <br>
										Бесплатно!! <br>
										Елена Потапова
									</td>
									<td>
										20:00-21:00 <br>
										Открытая группа <br>
										Фитнес -  <br>
										программа <br>
										Mind&Body <br>
										Дарья Короткова
									</td>
									<td></td>
									<td></td>
									<td></td>
									<td></td>
									<td></td>
								</tr>
							</tbody>
						</table>
					</div>
				</div>
			</div>
			<div class="col-md-3">
				<div class="next-direction-vn">
					<p class="text-center">
						Другие направления
					</p>
					<ul class="list-unstyled">
						<li><a href="#">Body Make</a></li>
						<li><a href="#">Magic Power</a></li>
						<li><a href="#">Strip parter</a></li>
						<li><a href="#">Стрипластика</a></li>
						<li><a href="#">Booty Dance</a></li>
					</ul>
				</div>
				<div class="list-ban">
                        <a href="#">
                            <img src="img/list-ban.png" class="img-responsive" alt="баннер">
                        </a>
                    </div>
                    <div class="vk-news">
                        <script type="text/javascript" src="//vk.com/js/api/openapi.js?122"></script>

                        <!-- VK Widget -->
                        <div id="vk_groups"></div>
                        <script type="text/javascript">
                        VK.Widgets.Group("vk_groups", {mode: 0, width: "auto", height: "400", color1: 'FFFFFF', color2: '2B587A', color3: '5B7FA6'}, 3772173);
                        </script>
                    </div>
			</div>
		</div>
	</div>
</div>