<div class="direction">
	<div class="container">
		<div class="row">
			<div class="col-md-9">
				<h2 class="text-center">
					Направление
				</h2>
				<p>
					Мечтаете научится танцевать? Школа танцев Top Dance имеет в своем арсенале более 120 групп, более 35 танцевальных курсов и фитнес - направлений. Многие из них являются экслюзивными, а богатый выбор предоставляет возможность подобрать программу, наиболее подходящую для вас. На нашем сайте вы найдете полный перечень и подробные описания всех стилей, которые вы можете научиться
				</p>
				<div class="row">
					<h3>Танцевальные направления</h3>
					<div class="col-md-3 mind">
						<div class="direction-case">
							<div class="direction-case-top"></div>
							<img src="img/direction.png" alt="направление" class="img-responsive">
							<div class="direction-case-bottom"></div>
						</div>
						<p>
							Mind Body
						</p>
					</div>
					<div class="col-md-3 mind">
						<div class="direction-case">
							<div class="direction-case-top"></div>
							<img src="img/direction.png" alt="направление" class="img-responsive">
							<div class="direction-case-bottom"></div>
						</div>
						<p>
							Стрипластика
						</p>
					</div>
					<div class="col-md-3 mind">
						<div class="direction-case">
							<div class="direction-case-top"></div>
							<img src="img/direction.png" alt="направление" class="img-responsive">
							<div class="direction-case-bottom"></div>
						</div>
						<p>
							Mind Body
						</p>
					</div>
					<div class="col-md-3 mind">
						<div class="direction-case">
							<div class="direction-case-top"></div>
							<img src="img/direction.png" alt="направление" class="img-responsive">
							<div class="direction-case-bottom"></div>
						</div>
						<p>
							Стрипластика
						</p>
					</div>
				</div>
				<div class="row">
					<h3>Танцевальные направления</h3>
					<div class="col-md-3 mind">
						<div class="direction-case">
							<div class="direction-case-top"></div>
							<img src="img/direction.png" alt="направление" class="img-responsive">
							<div class="direction-case-bottom"></div>
						</div>
						<p>
							Mind Body
						</p>
					</div>
					<div class="col-md-3 mind">
						<div class="direction-case">
							<div class="direction-case-top"></div>
							<img src="img/direction.png" alt="направление" class="img-responsive">
							<div class="direction-case-bottom"></div>
						</div>
						<p>
							Стрипластика
						</p>
					</div>
					<div class="col-md-3 mind">
						<div class="direction-case">
							<div class="direction-case-top"></div>
							<img src="img/direction.png" alt="направление" class="img-responsive">
							<div class="direction-case-bottom"></div>
						</div>
						<p>
							Mind Body
						</p>
					</div>
					<div class="col-md-3 mind">
						<div class="direction-case">
							<div class="direction-case-top"></div>
							<img src="img/direction.png" alt="направление" class="img-responsive">
							<div class="direction-case-bottom"></div>
						</div>
						<p>
							Стрипластика
						</p>
					</div>
				</div>
				<div class="row">
					<h3>Танцевальные направления</h3>
					<div class="col-md-3 mind">
						<div class="direction-case">
							<div class="direction-case-top"></div>
							<img src="img/direction.png" alt="направление" class="img-responsive">
							<div class="direction-case-bottom"></div>
						</div>
						<p>
							Mind Body
						</p>
					</div>
					<div class="col-md-3 mind">
						<div class="direction-case">
							<div class="direction-case-top"></div>
							<img src="img/direction.png" alt="направление" class="img-responsive">
							<div class="direction-case-bottom"></div>
						</div>
						<p>
							Mind Body
						</p>
					</div>
					<div class="col-md-3 mind">
						<div class="direction-case">
							<div class="direction-case-top"></div>
							<img src="img/direction.png" alt="направление" class="img-responsive">
							<div class="direction-case-bottom"></div>
						</div>
						<p>
							Mind Body
						</p>
					</div>
					<div class="col-md-3 mind">
						<div class="direction-case">
							<div class="direction-case-top"></div>
							<img src="img/direction.png" alt="направление" class="img-responsive">
							<div class="direction-case-bottom"></div>
						</div>
						<p>
							Mind Body
						</p>
					</div>
				</div>
			</div>
			<div class="col-md-3">
				<div class="list-ban">
                        <a href="#">
                            <img src="img/list-ban.png" class="img-responsive" alt="баннер">
                        </a>
                    </div>
                    <div class="vk-news">
                        <script type="text/javascript" src="//vk.com/js/api/openapi.js?122"></script>

                        <!-- VK Widget -->
                        <div id="vk_groups"></div>
                        <script type="text/javascript">
                        VK.Widgets.Group("vk_groups", {mode: 0, width: "auto", height: "400", color1: 'FFFFFF', color2: '2B587A', color3: '5B7FA6'}, 3772173);
                        </script>
                    </div>
                    <div class="girl-img">
                        <img src="img/girl-img.png" class="img-responsive" alt="девушка">
                    </div>
			</div>
		</div>
	</div>
</div>