

    <div class="container-fluid side-collapse-container">
        <section>
            <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                <!-- Indicators -->
                <ol class="carousel-indicators">
                    <li class="active" data-target="#carousel-example-generic" data-slide-to="0"></li>
                    <li class="" data-target="#carousel-example-generic" data-slide-to="1"></li>
                    <li class="" data-target="#carousel-example-generic" data-slide-to="2"></li>
                </ol>
        
                <!-- Wrapper for slides -->
                    <div class="carousel-caption">
                        <h3>школа танцев в москве</h3>
                        <button class="btn btn-default">
                            Получи приглашение на бесплатный урок
                        </button>
                    </div>
                <div class="carousel-inner">
                    <div class="item active">
                        <img src="img/slyder.png" alt="slyder">
                    </div>
                    <div class="item">
                        <img src="img/slyder.png" alt="slyder">
                    </div>
                    <div class="item">
                        <img src="img/slyder.png" alt="slyder">
                    </div>
                </div>
            </div>
        </section>
    </div>
    <div class="top-dance">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
              <h2 class="text-center">Top-Dance &mdash; современная школа танцев в Москве</h2>
              <p class="">
                Ищете недорогую школу танцев в Москве? И для Вас важно, чтобы процесс преподования был приятным и результативным? Тогда мы ждем Вас в мире энергии и позитива &laquo;Top Dance&raquo;! Студия танцев &laquo;Top Dance&raquo; &mdash; это место самореализации, движения, повышения Вашего танцевального уровня и раскрытия потенциала. Мы любим танцы, получаем удовольствие от своей работы, поэтому все занятия проходят в приятной легкой атмосфере. Сегодня &laquo;Top Dance&raquo; является одной из ведущих студий танцев Москвы, представляя возможность обучения в комфортной распологающей  обстановке. Если Вы уже занимались танцами, с нами Вы станете профессиональнее и техничнее. Если же Вы новичок, выбрать курс или программу по нужному направлению поможет профессиональный преподователь. Все группы формируются с учетом возраста и уровня подготовки, чтобы Вам было максимально интересно заниматься.
              </p>
          </div>
        </div>
        <div class="row text-center">
          <h2>
            Направления
          </h2>
          <div class="col-md-4">
            <p class="text-center">Mind&nbsp;&&nbsp;Body</p>
            <div class="img-case">
            <div class="img-case-top"></div>
              <img src="img/mind.png" alt="" class="img-responsive">
              <div class="img-case-bottom"></div>
            </div>
            <div class="clear"></div>
            <div class="button-dance">
                <a href="#" class="button-left">
                    Подробнее
                </a>
                <a href="#" class="button-right">
                    Записаться
                </a>
            </div>
          </div>
          <div class="col-md-4">
            <p class="text-center">Jazz Funk</p>
            <div class="img-case">
            <div class="img-case-top"></div>
              <img src="img/jass.png" alt="" class="img-responsive">
              <div class="img-case-bottom"></div>
            </div>
            <div class="clear"></div>
            <div class="button-dance">
                <a href="#" class="button-left">
                    Подробнее
                </a>
                <a href="#" class="button-right">
                    Записаться
                </a>
            </div>
          </div>
          <div class="col-md-4">
            <p class="text-center">Стрип-пластика</p>
            <div class="img-case">
            <div class="img-case-top"></div>
              <img src="img/strip.png" alt="" class="img-responsive">
              <div class="img-case-bottom"></div>
            </div>
            <div class="clear"></div>
            <div class="button-dance">
                <a href="#" class="button-left">
                    Подробнее
                </a>
                <a href="#" class="button-right">
                    Записаться
                </a>
            </div>
          </div>
        </div>
        <div class="row text-center">
            <button class="btn-lg btn-default tpdance">Больше направлений</button>
        </div>

      </div>
    </div>
    <!-- end top-dance -->
    <div class="perfomanse">
        <div class="container">
                <h2 class="text-left">
                    Нам уже более 8 лет.
                </h2>
                <span class="separator pull-left"></span>
                <p>
                    За 8 лет через двери нашей студии прошли более 2600 танцоров и танцовщиц. Успели поучаствовать в различных конкурсах и танцевальных состязаниях.
                </p>
                <p>
                    В команде Top Dance на данный момент 27 профессиональных танцоров. Освоили и стали обучать более 15 направлений танцев
                </p>
                <span class="separator pull-right"></span>
        </div>
    </div>
    <!-- end perfomanse -->
    <div class="video">
        <div class="container">
            <h2 class="text-center">
                Наши видео
            </h2>
            <div class="row">
                <div id="owl-example" class="owl-carousel">
                    <div> 
                        <a class="thumbnail" href="#">
                            <img alt="" src="img/play.png">
                        </a>
                    </div>
                    <div>
                        <a class="thumbnail" href="#">
                            <img alt="" src="img/play.png">
                        </a>
                    </div>
                    <div>
                        <a class="thumbnail" href="#">
                            <img alt="" src="img/play.png">
                        </a>
                    </div>
                    <div>
                        <a class="thumbnail" href="#">
                            <img alt="" src="img/play.png">
                        </a>
                    </div>
                    <div>
                        <a class="thumbnail" href="#">
                            <img alt="" src="img/play.png">
                        </a> 
                    </div>
                    <div>
                        <a class="thumbnail" href="#">
                            <img alt="" src="img/play.png">
                        </a>
                    </div>
                    <div>
                        <a class="thumbnail" href="#">
                            <img alt="" src="img/play.png">
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- end video -->
    <div class="price">
        <div class="container">
            <h2 class="text-center">
                Наши цены
            </h2>
            <div class="col-md-4 text-right">
                <div class="subscription text-center">
                    <p>Абонемент за 12 занятий</p>
                    <div class="border-line"></div>
                    <span>4500</span>
                    <div class="border-line"></div>
                    <p>Действует 30 дней</p>
                </div>
                <button class="btn btn-subscription">Заказать абонемент</button>
            </div>
            <div class="col-md-4 text-right">
                <div class="subscription text-center">
                    <p>Абонемент за 16 занятий</p>
                    <div class="border-line"></div>
                    <span>5000</span>
                    <div class="border-line"></div>
                    <p>Действует 30 дней</p>
                </div>
                <button class="btn btn-subscription">Заказать абонемент</button>
            </div>
            <div class="col-md-4 text-right">
                <div class="subscription text-center">
                    <p>Безлимитный абонемент</p>
                    <div class="border-line"></div>
                    <span>6900</span>
                    <div class="border-line"></div>
                    <p>Действует 30 дней</p>
                </div>
                <button class="btn btn-subscription">Заказать абонемент</button>
            </div>
            <div class="row text-center">
                <button class="btn btn-subscription">
                    Другие предложения
                </button>
            </div>
        </div>
    </div>
    <!-- end price -->
    <div class="recall">
        <div class="container">
            <h2 class="text-center">
                Что о нас говорят ученики
            </h2>
            <div class="row">
                <div class="col-md-8">
                    <div class="recall-block">
                        <div class="col-md-3">
                            <div class="recall-img">
                            <div class="recal-img-top"></div>
                                <img src="img/photo.png" alt="photo" class="img-responsive">
                                <div class="recal-img-bottom"></div>
                            </div>
                        </div>
                        <div class="col-md-9">
                            <h3>Евгений Махаловский 25 лет</h3>
                            <p>
                                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Mollitia doloremque sit, enim sint odio corporis illum perferendis, unde repellendus aut dolore doloribus minima qui ullam vel possimus magnam ipsa deleniti.
                            </p>
                        </div>
                    </div>
                    <div class="row text-center">
                        <button class="btn btn-recall">
                            Все отзывы
                        </button>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="vk">
                        <script type="text/javascript" src="//vk.com/js/api/openapi.js?122"></script>

                        <!-- VK Widget -->
                        <div id="vk_groups"></div>
                        <script type="text/javascript">
                        VK.Widgets.Group("vk_groups", {mode: 0, width: "auto", height: "400", color1: 'FFFFFF', color2: '2B587A', color3: '5B7FA6'}, 3772173);
                        </script>
                    </div>
                </div>
            </div>
            
        </div>
    </div>
    <!-- https://vk.com/top_dance_forever -->