<div class="open-class">
	<div class="container">
		<div class="row">
			<div class="col-md-9">
				<h2>
					Стартовала группа по jazz Funk!!
				</h2>
				<div class="b-open-class">
					<p class="data">
						06 июня 2016
					</p>
					<div class="b-open-class__item">
						<img src="img/open-class.png" alt="Juzz Funk" class="img-responsive">
					</div>
					<p class="open-class_info">
						Jazz Funk - это не конкретный стиль, а скорее смешение всевозможных направлений, которые сплетаются в уникальном стиле, рождаемом индивидуальным чувством вкуса хореографа и основанный на игре и единении контрастов.
					</p>
					<p class="open-class_info">
						Это наиболее доступный и естественный вид танца из всех существующих сегодня танцевальных стилей и направлений. В нем нет никаких конкретных правил и ограничений. Совмещение несовместимого делает этот танец загадочным и тем более привлекательным.
					</p>
					<p class="open-class_info">
						Несмотря на то, что этот стиль танца состоит из элементов, заимствованых из других танцевальных направлений, у него все же есть свое собственное лицо.
					</p>
				</div>
			</div>
			<div class="col-md-3">
				<div class="list-ban">
                        <a href="#">
                            <img src="img/list-ban.png" class="img-responsive" alt="баннер">
                        </a>
                    </div>
                    <div class="vk-news">
                        <script type="text/javascript" src="//vk.com/js/api/openapi.js?122"></script>

                        <!-- VK Widget -->
                        <div id="vk_groups"></div>
                        <script type="text/javascript">
                        VK.Widgets.Group("vk_groups", {mode: 0, width: "auto", height: "400", color1: 'FFFFFF', color2: '2B587A', color3: '5B7FA6'}, 3772173);
                        </script>
                    </div>
                    <!-- <div class="girl-img">
                        <img src="img/girl-img.png" class="img-responsive" alt="девушка">
                    </div> -->
				</div>
			</div>
		</div>
	</div>
</div>