<div class="price">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="col-md-9">
                    <h2>
                    Стоимость услуг школы танцев &laquo;Top Dance&raquo;
                    </h2>
                    <ul class="list-unstyled">
                        <li>Производство услуг <span>ООО &laquo;Топ-Данс&raquo;</span> вы соглашаетесь с условиями договора-оферты</li>
                        <li>Теперь вы можете оплатить абонемент, не выходя из дома!</li>
                        <li>реквизиты:</li>
                        <li>Сбербанк&mdash;<span>5469 3800 4372 4490</span></li>
                        <li>Альфа-банк&mdash;<span>5211 7827 4626 7225</span></li>
                        <li>при перезвоне денег на карту, указывайте пожалуйста, свое имя и фамилию, название абонемента</li>
                        <li>Телефон для связи: <span>8(495) 723-53-06</span></li>
                        <li>Постоянно действующие акции!</li>
                        <li>Приведи друга и получи скидку для друга и для себя по <span>700 руб</span> на абонемент.</li>
                    </ul>
                    <p>Если следующий абонемент покупается пока еще действует предыдущий, то скидка <span>350 руб.</span> При этом, следующий абонемент начинает действовать сразу же после окончания предыдущего.</p>
                    <p>Только для новых клиентов:</p>
                    <p></p>
                    <div class="price-table">
                        <div class="col-md-12">
                            <div class="panel">
                                <ul class="nav-tabs nav">
                                    <li class="active">
                                        <a href="#tab1" data-toggle="tab">
                                            Абонемент
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#tab2" data-toggle="tab">
                                            Индивидуальные занятия
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#tab3" data-toggle="tab">
                                            Спец курс "Шпагат"
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#tab4" data-toggle="tab">
                                            "Приват Танец"
                                        </a>
                                    </li>
                                </ul>
                            </div>
                            <div class="panel-body">
                                <div class="tab-content">
                                    <div class="tab-pane fade in active" id="tab1">
                                        <table class="table">
                                            <thead>
                                                <tr class="primary-tab">
                                                    <th>
                                                        Наименование
                                                    </th>
                                                    <th>
                                                        Цены
                                                    </th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td>
                                                        Пробный урок Разовое занятие
                                                    </td>
                                                    <td>
                                                        300р 500р
                                                    </td>
                                                </tr>
                                                <tr class="primary-tab">
                                                    <td>
                                                        Абонемент на 8 занятий (действует 30 дней)
                                                    </td>
                                                    <td>
                                                        3500р
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        Абонемент на 12 занятий с привязкой к педагогу (действует 30 дней)
                                                    </td>
                                                    <td>
                                                        3900р
                                                    </td>
                                                </tr>
                                                <tr class="primary-tab">
                                                    <td>
                                                        Абонемент на 12 занятий (действует 30 дней)
                                                    </td>
                                                    <td>
                                                        4500р
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        Абонемент на 16 занятий с привязкой к педагогу (действует 30 дней)
                                                    </td>
                                                    <td>
                                                        4900р
                                                    </td>
                                                </tr>
                                                <tr class="primary-tab">
                                                    <td>
                                                        Абонемент на 16 занятий (действует 30 дней)
                                                    </td>
                                                    <td>
                                                        5900р
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        Безлимитный абонемент (действует 30 дней)
                                                    </td>
                                                    <td>
                                                        6900р
                                                    </td>
                                                </tr>
                                                <tr class="primary-tab">
                                                    <td>
                                                        Безлимитный абонемент на 7 дней
                                                    </td>
                                                    <td>
                                                        2500р
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td></td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                    <div class="tab-pane fade" id="tab2">
                                        <table class="table">
                                            <thead>
                                                <tr class="primary-tab">
                                                    <th>
                                                        Наименование
                                                    </th>
                                                    <th>
                                                        Цены
                                                    </th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td>
                                                        Пробный урок Разовое занятие
                                                    </td>
                                                    <td>
                                                        300р 500р
                                                    </td>
                                                </tr>
                                                <tr class="primary-tab">
                                                    <td>
                                                        Абонемент на 8 занятий (действует 30 дней)
                                                    </td>
                                                    <td>
                                                        3500р
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        Абонемент на 12 занятий с привязкой к педагогу (действует 30 дней)
                                                    </td>
                                                    <td>
                                                        3900р
                                                    </td>
                                                </tr>
                                                <tr class="primary-tab">
                                                    <td>
                                                        Абонемент на 12 занятий (действует 30 дней)
                                                    </td>
                                                    <td>
                                                        4500р
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        Абонемент на 16 занятий с привязкой к педагогу (действует 30 дней)
                                                    </td>
                                                    <td>
                                                        4900р
                                                    </td>
                                                </tr>
                                                <tr class="primary-tab">
                                                    <td>
                                                        Абонемент на 16 занятий (действует 30 дней)
                                                    </td>
                                                    <td>
                                                        5900р
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        Безлимитный абонемент (действует 30 дней)
                                                    </td>
                                                    <td>
                                                        6900р
                                                    </td>
                                                </tr>
                                                <tr class="primary-tab">
                                                    <td>
                                                        Безлимитный абонемент на 7 дней
                                                    </td>
                                                    <td>
                                                        2500р
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td></td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                    <div class="tab-pane fade" id="tab3">
                                        <table class="table">
                                            <thead>
                                                <tr class="primary-tab">
                                                    <th>
                                                        Наименование
                                                    </th>
                                                    <th>
                                                        Цены
                                                    </th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td>
                                                        Пробный урок Разовое занятие
                                                    </td>
                                                    <td>
                                                        300р 500р
                                                    </td>
                                                </tr>
                                                <tr class="primary-tab">
                                                    <td>
                                                        Абонемент на 8 занятий (действует 30 дней)
                                                    </td>
                                                    <td>
                                                        3500р
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        Абонемент на 12 занятий с привязкой к педагогу (действует 30 дней)
                                                    </td>
                                                    <td>
                                                        3900р
                                                    </td>
                                                </tr>
                                                <tr class="primary-tab">
                                                    <td>
                                                        Абонемент на 12 занятий (действует 30 дней)
                                                    </td>
                                                    <td>
                                                        4500р
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        Абонемент на 16 занятий с привязкой к педагогу (действует 30 дней)
                                                    </td>
                                                    <td>
                                                        4900р
                                                    </td>
                                                </tr>
                                                <tr class="primary-tab">
                                                    <td>
                                                        Абонемент на 16 занятий (действует 30 дней)
                                                    </td>
                                                    <td>
                                                        5900р
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        Безлимитный абонемент (действует 30 дней)
                                                    </td>
                                                    <td>
                                                        6900р
                                                    </td>
                                                </tr>
                                                <tr class="primary-tab">
                                                    <td>
                                                        Безлимитный абонемент на 7 дней
                                                    </td>
                                                    <td>
                                                        2500р
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td></td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                    <div class="tab-pane fade" id="tab4">
                                        <table class="table">
                                            <thead>
                                                <tr class="primary-tab">
                                                    <th>
                                                        Наименование
                                                    </th>
                                                    <th>
                                                        Цены
                                                    </th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td>
                                                        Пробный урок Разовое занятие
                                                    </td>
                                                    <td>
                                                        300р 500р
                                                    </td>
                                                </tr>
                                                <tr class="primary-tab">
                                                    <td>
                                                        Абонемент на 8 занятий (действует 30 дней)
                                                    </td>
                                                    <td>
                                                        3500р
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        Абонемент на 12 занятий с привязкой к педагогу (действует 30 дней)
                                                    </td>
                                                    <td>
                                                        3900р
                                                    </td>
                                                </tr>
                                                <tr class="primary-tab">
                                                    <td>
                                                        Абонемент на 12 занятий (действует 30 дней)
                                                    </td>
                                                    <td>
                                                        4500р
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        Абонемент на 16 занятий с привязкой к педагогу (действует 30 дней)
                                                    </td>
                                                    <td>
                                                        4900р
                                                    </td>
                                                </tr>
                                                <tr class="primary-tab">
                                                    <td>
                                                        Абонемент на 16 занятий (действует 30 дней)
                                                    </td>
                                                    <td>
                                                        5900р
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        Безлимитный абонемент (действует 30 дней)
                                                    </td>
                                                    <td>
                                                        6900р
                                                    </td>
                                                </tr>
                                                <tr class="primary-tab">
                                                    <td>
                                                        Безлимитный абонемент на 7 дней
                                                    </td>
                                                    <td>
                                                        2500р
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td></td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="list-ban">
                        <a href="#">
                            <img src="img/list-ban.png" class="img-responsive" alt="баннер">
                        </a>
                    </div>
                    <div class="vk-news">
                        <script type="text/javascript" src="//vk.com/js/api/openapi.js?122"></script>

                        <!-- VK Widget -->
                        <div id="vk_groups"></div>
                        <script type="text/javascript">
                        VK.Widgets.Group("vk_groups", {mode: 0, width: "auto", height: "400", color1: 'FFFFFF', color2: '2B587A', color3: '5B7FA6'}, 3772173);
                        </script>
                    </div>
                    <div class="girl-img">
                        <img src="img/girl-img.png" class="img-responsive" alt="девушка">
                    </div>
                </div>
            </div>
        </div>