<div class="schedule">
	<div class="container">
		<div class="row">
			<h2>
				Расписание
			</h2>
			<div class="col-md-12">
				<ul class="list-unstyled list-li">
					<li>
						<label>
						    <input type="checkbox" class="checkbox" checked> Понедельник
						</label>
					</li>
					<li>
							<label>
								<input type="checkbox" class="checkbox"> Вторник
							</label>
					</li>
					<li>
							<label>
								<input type="checkbox" class="checkbox"> Среда
							</label>
					</li>
					<li>
							<label>
								<input type="checkbox" class="checkbox"> Четверг
							</label>
					</li>
					<li>
							<label>
								<input type="checkbox" class="checkbox"> Пятница
							</label>
					</li>
					<li>
							<label>
								<input type="checkbox" class="checkbox"> Суббота
							</label>
					</li>
					<li>
							<label>
								<input type="checkbox" class="checkbox"> Воскресенье
							</label>
					</li>
					<li>
						<select id="clock">
						    <option value="hide">12:00</option>
						    <option value="12:00">12:30</option>
						    <option value="13:00">13:00</option>
						    <option value="14:00">14:00</option>
						    <option value="15:00">15:00</option>
						</select> 
					</li>
					<li>
						<select id="clock">
						    <option value="hide">21:00</option>
						    <option value="12:00">21:30</option>
						    <option value="13:00">22:00</option>
						    <option value="14:00">23:00</option>
						    <option value="15:00">02:00</option>
						</select> 
					</li>
				</ul>
			</div>
		</div>
		<div class="row">
			<div class="col-md-12">
				<div class="shedule__item">
					<ul class="list-unstyled">
						<li>
							<a href="#">
								Body Make
							</a>
						</li>
						<li>
							<a href="#">
								Magic Power
							</a>
						</li>
						<li>
							<a href="#">
								Strip Parter
							</a>
						</li>
						<li>
							<a href="#">
								Стрипластика
							</a>
						</li>
						<li>
							<a href="#">
								Booty Dance
							</a>
						</li>
					</ul>
				</div>

				<div class="b-shedule">
					<p>
						Booty Dance
					</p>
					<div class="table-shedule">
						<table>
							<thead>
								<tr>
									<th></th>
									<th>
										Понедельник
									</th>
									<th>
										Вторник
									</th>
									<th>
										Среда
									</th>
									<th>
										Четверг
									</th>
									<th>
										Пятница
									</th>
									<th>
										Суббота
									</th>
									<th>
										Воскресенье
									</th>
									<th>
										Наличие мест
									</th>
								</tr>
							</thead>
							<tbody>
								<tr class="primary-tab">
									<td>
										<a href="#">
											Записаться в группу
										</a>
									</td>
									<td>
										12:00 - 13:00 <br>
										Открытый урок! <br>
										Бесплатно! <br>
										Елена Потапова
									</td>
									<td></td>
									<td></td>
									<td></td>
									<td></td>
									<td></td>
									<td></td>
									<td>
										5
									</td>
								</tr>
								<tr>
									<td></td>
									<td></td>
									<td></td>
									<td></td>
									<td></td>
									<td></td>
									<td></td>
									<td></td>
									<td></td>
								</tr>
								<tr class="primary-tab">
									<td><a href="#"></a></td>
									<td><a href="#"></a></td>
									<td><a href="#"></a></td>
									<td><a href="#"></a></td>
									<td><a href="#"></a></td>
									<td><a href="#"></a></td>
									<td><a href="#"></a></td>
									<td><a href="#"></a></td>
									<td><a href="#"></a></td>
								</tr>
							</tbody>
						</table>
					</div>
					<p>
						Стрипластика
					</p>
					<div class="table-shedule">
						<table>
							<thead>
								<tr>
									<th></th>
									<th>
										Понедельник
									</th>
									<th>
										Вторник
									</th>
									<th>
										Среда
									</th>
									<th>
										Четверг
									</th>
									<th>
										Пятница
									</th>
									<th>
										Суббота
									</th>
									<th>
										Воскресенье
									</th>
									<th>
										Наличие мест
									</th>
								</tr>
							</thead>
							<tbody>
								<tr class="primary-tab">
									<td>
										<a href="#">
											Записаться в группу
										</a>
									</td>
									<td></td>
									<td></td>
									<td></td>
									<td>
										18:00 - 19:00 <br>
										Елена Семина	
									</td>
									<td></td>
									<td></td>
									<td></td>
									<td>
										5
									</td>
								</tr>
								<tr>
									<td>
										<a href="#">
											Записаться в группу
										</a>
									</td>
									<td></td>
									<td></td>
									<td></td>
									<td></td>
									<td>
										20:00 - 21:00 <br>
										Stretching <br>
										Дарья Короткова
									</td>
									<td></td>
									<td></td>
									<td>10</td>
								</tr>
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>