<div class="teachers">
	<div class="container">
		<div class="row text-center">
			<h2>
				Преподаватели
			</h2>
		</div>
		<div class="portfolio-filter">
			<ul class="list-unstyled">
				<li class="active"><a href="#" data-rel="all">Все</a></li>
				<li><a href="#" data-rel="body_make">Body Make</a></li>
				<li><a href="#" data-rel="magic_power">Magic Power</a></li>
				<li><a href="#" data-rel="strip_parter">Strip Parter</a></li>
				<li><a href="#" data-rel="strip">Стрипластика</a></li>
				<li><a href="#" data-rel="booty_dance">Booty Dance</a></li>
			</ul>
			<div id="portfolio">
				<div class="body_make all col-md-3">
				    <div class="b-teachers">
					<img src="img/teacher.png" alt="учитель" class="img-responsive">
					<div class="info-teachers">
						<div class="item-teachers">
						<i class="fa fa-user" aria-hidden="true"></i>
							<p>
								Алиса Андерсон
							</p>
							<a href="?action=teachers__mini">
								Body Make
							</a>
						</div>
					</div>
				</div>
				</div>
				<div class="magic_power all col-md-3">
				    <div class="b-teachers">
					<img src="img/teacher.png" alt="учитель" class="img-responsive">
					<div class="info-teachers">
						<div class="item-teachers">
						<i class="fa fa-user" aria-hidden="true"></i>
							<p>
								Алиса Андерсон
							</p>
							<a href="?action=teachers__mini">
								Body Make
							</a>
						</div>
					</div>
				</div>
				</div>
				<div class="body_make all col-md-3">
				    <div class="b-teachers">
					<img src="img/teacher.png" alt="учитель" class="img-responsive">
					<div class="info-teachers">
						<div class="item-teachers">
						<i class="fa fa-user" aria-hidden="true"></i>
							<p>
								Алиса Андерсон
							</p>
							<a href="?action=teachers__mini">
								Body Make
							</a>
						</div>
					</div>
				</div>
				</div>
				<div class="body_make all col-md-3">
				    <div class="b-teachers">
					<img src="img/teacher.png" alt="учитель" class="img-responsive">
					<div class="info-teachers">
						<div class="item-teachers">
						<i class="fa fa-user" aria-hidden="true"></i>
							<p>
								Алиса Андерсон
							</p>
							<a href="?action=teachers__mini">
								Body Make
							</a>
						</div>
					</div>
				</div>
				</div>
				<div class="strip_parter all col-md-3">
				    <div class="b-teachers">
					<img src="img/teacher.png" alt="учитель" class="img-responsive">
					<div class="info-teachers">
						<div class="item-teachers">
						<i class="fa fa-user" aria-hidden="true"></i>
							<p>
								Алиса Андерсон
							</p>
							<a href="?action=teachers__mini">
								Body Make
							</a>
						</div>
					</div>
				</div>
				</div>
				<div class="magic_power all col-md-3">
				    <div class="b-teachers">
					<img src="img/teacher.png" alt="учитель" class="img-responsive">
					<div class="info-teachers">
						<div class="item-teachers">
						<i class="fa fa-user" aria-hidden="true"></i>
							<p>
								Алиса Андерсон
							</p>
							<a href="?action=teachers__mini">
								Body Make
							</a>
						</div>
					</div>
				</div>
				</div>
				<div class="strip_parter all col-md-3">
				    <div class="b-teachers">
					<img src="img/teacher.png" alt="учитель" class="img-responsive">
					<div class="info-teachers">
						<div class="item-teachers">
						<i class="fa fa-user" aria-hidden="true"></i>
							<p>
								Алиса Андерсон
							</p>
							<a href="?action=teachers__mini">
								Body Make
							</a>
						</div>
					</div>
				</div>
				</div>
				<div class="booty_dance all col-md-3">
				    <div class="b-teachers">
					<img src="img/teacher.png" alt="учитель" class="img-responsive">
					<div class="info-teachers">
						<div class="item-teachers">
						<i class="fa fa-user" aria-hidden="true"></i>
							<p>
								Алиса Андерсон
							</p>
							<a href="?action=teachers__mini">
								Body Make
							</a>
						</div>
					</div>
				</div>
				</div>
				<div class="strip all col-md-3">
				    <div class="b-teachers">
					<img src="img/teacher.png" alt="учитель" class="img-responsive">
					<div class="info-teachers">
						<div class="item-teachers">
						<i class="fa fa-user" aria-hidden="true"></i>
							<p>
								Алиса Андерсон
							</p>
							<a href="?action=teachers__mini">
								Body Make
							</a>
						</div>
					</div>
				</div>
				</div>
				<div class="booty_dance all col-md-3">
				    <div class="b-teachers">
					<img src="img/teacher.png" alt="учитель" class="img-responsive">
					<div class="info-teachers">
						<div class="item-teachers">
						<i class="fa fa-user" aria-hidden="true"></i>
							<p>
								Алиса Андерсон
							</p>
							<a href="?action=teachers__mini">
								Body Make
							</a>
						</div>
					</div>
				</div>
				</div>
				<div class="booty_dance all col-md-3">
				    <div class="b-teachers">
					<img src="img/teacher.png" alt="учитель" class="img-responsive">
					<div class="info-teachers">
						<div class="item-teachers">
						<i class="fa fa-user" aria-hidden="true"></i>
							<p>
								Алиса Андерсон
							</p>
							<a href="?action=teachers__mini">
								Body Make
							</a>
						</div>
					</div>
				</div>
				</div>
				<div class="strip all col-md-3">
				    <div class="b-teachers">
					<img src="img/teacher.png" alt="учитель" class="img-responsive">
					<div class="info-teachers">
						<div class="item-teachers">
						<i class="fa fa-user" aria-hidden="true"></i>
							<p>
								Алиса Андерсон
							</p>
							<a href="?action=teachers__mini">
								Body Make
							</a>
						</div>
					</div>
				</div>
				</div>
				<div class="booty_dance all col-md-3">
				    <div class="b-teachers">
					<img src="img/teacher.png" alt="учитель" class="img-responsive">
					<div class="info-teachers">
						<div class="item-teachers">
						<i class="fa fa-user" aria-hidden="true"></i>
							<p>
								Алиса Андерсон
							</p>
							<a href="?action=teachers__mini">
								Body Make
							</a>
						</div>
					</div>
				</div>
				</div>
				<div class="booty_dance all col-md-3">
				    <div class="b-teachers">
					<img src="img/teacher.png" alt="учитель" class="img-responsive">
					<div class="info-teachers">
						<div class="item-teachers">
						<i class="fa fa-user" aria-hidden="true"></i>
							<p>
								Алиса Андерсон
							</p>
							<a href="?action=teachers__mini">
								Body Make
							</a>
						</div>
					</div>
				</div>
				</div>
				<div class="booty_dance all col-md-3">
				    <div class="b-teachers">
					<img src="img/teacher.png" alt="учитель" class="img-responsive">
					<div class="info-teachers">
						<div class="item-teachers">
						<i class="fa fa-user" aria-hidden="true"></i>
							<p>
								Алиса Андерсон
							</p>
							<a href="?action=teachers__mini">
								Body Make
							</a>
						</div>
					</div>
				</div>
				</div>
				<div class="booty_dance all col-md-3">
				    <div class="b-teachers">
					<img src="img/teacher.png" alt="учитель" class="img-responsive">
					<div class="info-teachers">
						<div class="item-teachers">
						<i class="fa fa-user" aria-hidden="true"></i>
							<p>
								Алиса Андерсон
							</p>
							<a href="?action=teachers__mini">
								Body Make
							</a>
						</div>
					</div>
				</div>
				</div>
			</div>
		</div>
	</div>
</div>