<div class="teachers__mini">
	<div class="container">
		<div class="row">
			<h2>
			Расписание
			</h2>
			<div class="col-md-12">
				<div class="col-md-3">
					<div class="b-teachers__mini">
						<div class="mini-b-top"></div>
						<div class="mini-b-bottom"></div>
						<img src="img/girl-img.png" alt="Учитель" class="img-responsive">
					</div>
				</div>
				<div class="col-md-9">
					<h3>
					София Андерсон
					</h3>
					<p>
						<span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo quo, doloremque impedit reiciendis nobis deserunt, corrupti sapiente consequatur repellat animi, ipsum repudiandae iusto exercitationem quos laboriosam aliquid quisquam dolore totam!</span>
						<span>Praesentium voluptatum adipisci nihil a quasi illo, mollitia cupiditate. Culpa laboriosam, id, quia quisquam minima voluptates velit sed. Repellat rem nemo adipisci, temporibus placeat nobis explicabo eligendi aliquid aperiam eum.</span>
						<span>Minus repellat blanditiis, consequatur officiis veritatis dignissimos fugit aut nam atque quo sequi eaque saepe explicabo, modi veniam pariatur non iste nisi quasi quisquam. Voluptatem numquam, quo quidem animi ipsam?</span>
					</p>
				</div>
			</div>
			<h2>
			Видео
			</h2>
			<div class="row">
				<div id="owl-example" class="owl-carousel">
					<div>
						<a class="thumbnail" href="#">
							<img alt="" src="img/play.png">
						</a>
					</div>
					<div>
						<a class="thumbnail" href="#">
							<img alt="" src="img/play.png">
						</a>
					</div>
					<div>
						<a class="thumbnail" href="#">
							<img alt="" src="img/play.png">
						</a>
					</div>
					<div>
						<a class="thumbnail" href="#">
							<img alt="" src="img/play.png">
						</a>
					</div>
					<div>
						<a class="thumbnail" href="#">
							<img alt="" src="img/play.png">
						</a>
					</div>
					<div>
						<a class="thumbnail" href="#">
							<img alt="" src="img/play.png">
						</a>
					</div>
					<div>
						<a class="thumbnail" href="#">
							<img alt="" src="img/play.png">
						</a>
					</div>
				</div>
			</div>
			<h2>
			Фото
			</h2>
			<div class="row">
				<div class="col-md-3">
					<div class="photo">
						<img src="img/mini.png" alt="Фото" class="img-respponsive">
					</div>
				</div>
				<div class="col-md-3">
					<div class="photo">
						<img src="img/mini.png" alt="Фото" class="img-respponsive">
					</div>
				</div>
				<div class="col-md-3">
					<div class="photo">
						<img src="img/mini.png" alt="Фото" class="img-respponsive">
					</div>
				</div>
				<div class="col-md-3">
					<div class="photo">
						<img src="img/mini.png" alt="Фото" class="img-respponsive">
					</div>
				</div>
			</div>
			<div class="row">
				<!-- <div class="span7"> -->
					<div class="widget stacked widget-table action-table">
						<div class="widget-header">
							<ul class="list-unstyled">
								<li>
									<a href="#">
										Body Make
									</a>
								</li>
								<li>
									<a href="#">
										Magic Power
									</a>
								</li>
								<li>
									<a href="#">
										Strip Parter
									</a>
								</li>
								<li>
									<a href="#">
										Стриппластика
									</a>
								</li>
								<li>
									<a href="#">
										Booty Dance
									</a>
								</li>
							</ul>
						</div> <!-- /widget-header -->
						<div class="widget-content">
							<table class="table table-striped table-responsive">
								<thead>
									<tr>
										<th>Понедельник</th>
										<th>Вторник</th>
										<th>Среда</th>
										<th>Четверг</th>
										<th>Пятница</th>
										<th>Суббота</th>
										<th>Воскресенье</th>
									</tr>
								</thead>
								<tbody>
									<tr>
										<td>
											<p>
												12.00 - 13.00 <br> София Андерсон<br> Записаться
											</p>
										</td>
										<td class="border-yellow">
											<p>20.00 - 21.00 <br> Открытая группа. <br> Фитнес - программа <br> Mind & Body <br>София Андерсон</p>
										</td>
										<td class="border-yellow"></td>
										<td class="border-yellow"></td>
										<td class="border-yellow"></td>
										<td class="border-yellow"></td>
										<td></td>
									</tr>
								</tbody>
							</table>

							<p>
								<a href="?action=price">
									Индивидуальные занятия с педагогом
								</a>
							</p>
						</div> <!-- /widget-content -->
					</div> <!-- /widget -->
				<!-- </div> -->
			</div>
		</div>
	</div>
</div>