<div class="footer">
        <div class="container">
            <div class="row">
                <div class="col-md-4 col-xs-12">
                    <div class="footer-nav">
                        <p>Навигация</p>
                        <div class="footer-menu ">
                            <ul class="list-unstyled">
                                <li><a href="#">Расписание</a></li>
                                <li><a href="?action=price">Прайс</a></li>
                                <li><a href="?action=open-class">Openclass и акции</a></li>
                                <li><a href="?action=teachers">Педагоги</a></li>
                            </ul>
                            <ul class="list-unstyled">
                                <li><a href="?action=direction">Направление</a></li>
                                <li><a href="#">Галерея</a></li>
                                <li><a href="#">Отзывы</a></li>
                                <li><a href="#">Контакты</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 col-xs-12 pull-right">
                        <div class="contact">
                            <p>
                                Контакты
                            </p>
                                <div class="contact-info">
                                    <a href="index.php"><img src="img/logo.png" alt="logo" class="img-responsive"></a>
                                    <p>Тел: <span>+7(495) 723-53-06</span></p>
                                    <p>Почта: <span>info@top-dance.ru</span></p>
                                    <p>Адрес: <span>М.Третьяковская/Новокузнецкая/Полянка ул.Большой Ордынский переулок д.4</span></p>
                                    <button class="btn btn-default">
                                        Заказать звонок&nbsp;<i class="fa fa-angle-right" aria-hidden="true"></i>
                                    </button>
                                </div>
                        </div>
                    </div>
                    <div class="col-md-4 col-xs-12">
                        <div class="smm text-center">
                            <a href="#">
                                <i class="fa fa-vk" aria-hidden="true"></i>
                            </a>
                            <a href="#">
                                <i class="fa fa-facebook" aria-hidden="true"></i>
                            </a>
                            <a href="#">
                                 <i class="fa fa-youtube" aria-hidden="true"></i>
                            </a>
                            <a href="#">
                                 <i class="fa fa-instagram" aria-hidden="true"></i>
                            </a>
                        </div>
                    </div>
                    <div class="col-md-8">
                        <div class="col-xs-6">
                            <p class="coopyright">&copy; 2008-2016 Top-Dance. Все права защищены.</p>
                        </div>
                        <div class="col-xs-6">
                             <div class="rise text-center">
                            <p>
                                Разработано
                            </p>
                            <a href="http://a-rise.ru/" target="_blank" class="logo-rise"></a>
                        </div>
                        </div>
                    </div>
            </div>
        </div>
    </div>
    <!--end footer  -->
    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script> -->
    <script src="js/jquery.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/owl.carousel.js"></script>
    <script src="js/scripts.js"></script>
  </body>
</html>