<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>TopDance</title>
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="css/style.css">
    <link rel="stylesheet" href="css/media.css">
    <link rel="stylesheet" href="css/owl.carousel.css">
    <link rel="stylesheet" href="css/owl.theme.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <div class="navigation">
        <div class="container">
            <a class="logo col-md-2 col-sm-2 " href="index.php">
                <img src="img/logo1.png" alt="" class="img-responsive">
            </a>
            <div class="nav-toggle hamburger">
                <span></span>
                <span></span>
                <span></span>
            </div>
                <div class="adress text-right">
                    <span class="">
                        М.Третьяковская/Новокузнецкая/Полянка. ул. Большой Ордынский переулок д.4
                    </span><br>
                </div>
            <div class="menuContacts col-md-10 col-sm-10">
                
                <ul class="list-unstyled menu text-center">
                    <li><a href="?action=schedule">Расписание</a></li>
                    <li><a href="?action=price">Прайс</a></li>
                    <li><a href="?action=open-class">Openclass и акции</a></li>
                    <li><a href="?action=teachers">Педагоги</a></li>
                    <li><a href="?action=direction">Направления</a></li>
                    <li><a href="#">О нас</a></li>
                    <li><a href="#">Отзывы</a></li>
                    <li><a href="#">Контакты</a></li>
                </ul>
            </div>
                <div class="info">
                    <span class="tel ">
                        +7999 999 99 99
                    </span>
                    <br>
                    <div class="social-icon">
                        <i class="fa fa-vk " aria-hidden="true"></i>
                        <i class="fa fa-facebook " aria-hidden="true"></i>
                        <i class="fa fa-youtube " aria-hidden="true"></i>
                        <i class="fa fa-instagram " aria-hidden="true"></i>
                    </div>
                    <br>
                    <button class="btn btn-default top">
                        Заказать звонок
                    </button>
                </div>

        </div>
    </div>